# DDS 에서 공통으로 사용되는 내용

STROBE_TIME_DATA_LIST = {"StrobeTime"}

 # ts.kim : 20230828 : PMD-36 : 구독하고 싶은 데이터 셋트 생성
MCS_CT_DATA_LIST =  { "OPRUN", "TURNAROUND_TIME0", "TURNAROUND_TIME1","TRANSFER_TIME0", "TRANSFER_TIME1", "LANE_INSP0", "LANE_INSP1",
                      "PCB_INSP", "PCB_INSP0", "PCB_INSP1", "FID_MOVE", "FID_MOVE0", "FID_MOVE1", "FID_INSP", "FID_INSP0", "FID_INSP1",
                      "FOV_MOVE", "FOV_MOVE0", "FOV_MOVE1", "FOV_INSP", "FOV_INSP0", "FOV_INSP1", 
                      "PSMEMA_IN", "PSMEMA_IN0", "PSMEMA_IN1",
                      "PSMEMA_OUT", "PSMEMA_OUT0", "PSMEMA_OUT1",       
                      "NSMEMA_IN", "NSMEMA_IN0", "NSMEMA_IN1",       
                      "NSMEMA_OUT", "NSMEMA_OUT0", "NSMEMA_OUT1",       
                      "NG_BUFFER", "NG_BUFFER0", "NG_BUFFER1"                             
                      }
                  
MCS_PCB_STATUS_DATA_LIST = {
                            "NOT_EXIST_F_EN",
                            "NOT_EXIST_F_WK",
                            "NOT_EXIST_F_EX",
                            "NOT_EXIST_R_EN",
                            "NOT_EXIST_R_WK",
                            "NOT_EXIST_R_EX",
                            "PCB_IN_STATUS_F_EN",
                            "PCB_IN_STATUS_F_WK",
                            "PCB_IN_STATUS_F_EX", 
                            "PCB_IN_STATUS_R_EN", 
                            "PCB_IN_STATUS_R_WK", 
                            "PCB_IN_STATUS_R_EX", 
                            "PCB_INCOME_PASSING_F_EN",
                            "PCB_INCOME_PASSING_F_WK",
                            "PCB_INCOME_PASSING_F_EX",
                            "PCB_INCOME_PASSING_R_EN",
                            "PCB_INCOME_PASSING_R_WK",
                            "PCB_INCOME_PASSING_R_EX", 
                            "PCB_JUST_PASSED_ENTRY_IN_STATUS_F_EN",
                            "PCB_JUST_PASSED_ENTRY_IN_STATUS_F_WK",
                            "PCB_JUST_PASSED_ENTRY_IN_STATUS_F_EX",
                            "PCB_JUST_PASSED_ENTRY_IN_STATUS_R_EN",
                            "PCB_JUST_PASSED_ENTRY_IN_STATUS_R_WK",
                            "PCB_JUST_PASSED_ENTRY_IN_STATUS_R_EX",
					        "PCB_ENTRY_PASSED_INCOME_PASSING_F_EN",
                            "PCB_ENTRY_PASSED_INCOME_PASSING_F_WK",
                            "PCB_ENTRY_PASSED_INCOME_PASSING_F_EX",
                            "PCB_ENTRY_PASSED_INCOME_PASSING_R_EN",
                            "PCB_ENTRY_PASSED_INCOME_PASSING_R_WK",
                            "PCB_ENTRY_PASSED_INCOME_PASSING_R_EX",
                            "PCB_WORK_STATUS_F_EN",
                            "PCB_WORK_STATUS_F_WK",
                            "PCB_WORK_STATUS_F_EX",
                            "PCB_WORK_STATUS_R_EN",
                            "PCB_WORK_STATUS_R_WK",
                            "PCB_WORK_STATUS_R_EX",
                            "PCB_WAIT_INSP_DONE_STATUS_F_EN",
                            "PCB_WAIT_INSP_DONE_STATUS_F_WK",
                            "PCB_WAIT_INSP_DONE_STATUS_F_EX",
                            "PCB_WAIT_INSP_DONE_STATUS_R_EN",
                            "PCB_WAIT_INSP_DONE_STATUS_R_WK",
                            "PCB_WAIT_INSP_DONE_STATUS_R_EX",
                            "PCB_INSP_DONE_STATUS_F_EN",
                            "PCB_INSP_DONE_STATUS_F_WK",
                            "PCB_INSP_DONE_STATUS_F_EX",
                            "PCB_INSP_DONE_STATUS_R_EN",
                            "PCB_INSP_DONE_STATUS_R_WK",
                            "PCB_INSP_DONE_STATUS_R_EX",
                            "PCB_OUTLET_PASSING_F_EN",
                            "PCB_OUTLET_PASSING_F_WK",
                            "PCB_OUTLET_PASSING_F_EX",
                            "PCB_OUTLET_PASSING_R_EN",
                            "PCB_OUTLET_PASSING_R_WK",
                            "PCB_OUTLET_PASSING_R_EX",
                            "PCB_OUT_STATUS_F_EN",
                            "PCB_OUT_STATUS_F_WK",
                            "PCB_OUT_STATUS_F_EX",
                            "PCB_OUT_STATUS_R_EN",
                            "PCB_OUT_STATUS_R_WK",
                            "PCB_OUT_STATUS_R_EX",
                            "PCB_OUT_NEXT_STATUS",
                            "PCB_OUT_NEXT_DONE_STATUS_F_EN",
                            "PCB_OUT_NEXT_DONE_STATUS_F_WK",
                            "PCB_OUT_NEXT_DONE_STATUS_F_EX",
                            "PCB_OUT_NEXT_DONE_STATUS_R_EN",
                            "PCB_OUT_NEXT_DONE_STATUS_R_WK",
                            "PCB_OUT_NEXT_DONE_STATUS_R_EX",
					        "PCB_IN_JAM_F_EN",
                            "PCB_IN_JAM_F_WK",
                            "PCB_IN_JAM_F_EX",
                            "PCB_IN_JAM_R_EN",
                            "PCB_IN_JAM_R_WK",
                            "PCB_IN_JAM_R_EX",
                            "PCB_OUT_JAM_F_EN",
                            "PCB_OUT_JAM_F_WK",
                            "PCB_OUT_JAM_F_EX",
                            "PCB_OUT_JAM_R_EN",
                            "PCB_OUT_JAM_R_WK",
                            "PCB_OUT_JAM_R_EX"
                            }

KYI_DATA_LIST =  {"GrabStart", "GrabEnd", "GrabberStart", "GrabberEnd", "GrabberCommandStart", "GrabberCommandEnd",
                  "GrabberReinitStart", "GrabberReinitEnd", "GrabDoneStart", "GrabDoneEnd"
                  }