# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visual_analyzer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(2000, 865)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.scroll_strobe = QtWidgets.QScrollArea(self.centralwidget)
        self.scroll_strobe.setGeometry(QtCore.QRect(310, 30, 120, 80))
        self.scroll_strobe.setWidgetResizable(False)
        self.scroll_strobe.setObjectName("scroll_strobe")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 118, 78))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scroll_strobe.setWidget(self.scrollAreaWidgetContents)
        self.scroll_mcs_ct = QtWidgets.QScrollArea(self.centralwidget)
        self.scroll_mcs_ct.setGeometry(QtCore.QRect(490, 30, 120, 80))
        self.scroll_mcs_ct.setWidgetResizable(False)
        self.scroll_mcs_ct.setObjectName("scroll_mcs_ct")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 118, 78))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.scroll_mcs_ct.setWidget(self.scrollAreaWidgetContents_3)
        self.scroll_mcs_pcb = QtWidgets.QScrollArea(self.centralwidget)
        self.scroll_mcs_pcb.setGeometry(QtCore.QRect(690, 30, 120, 80))
        self.scroll_mcs_pcb.setWidgetResizable(False)
        self.scroll_mcs_pcb.setObjectName("scroll_mcs_pcb")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 118, 78))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.scroll_mcs_pcb.setWidget(self.scrollAreaWidgetContents_4)
        self.output = QtWidgets.QListWidget(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(310, 300, 256, 192))
        self.output.setObjectName("output")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2000, 21))
        self.menubar.setObjectName("menubar")
        self.menuDB = QtWidgets.QMenu(self.menubar)
        self.menuDB.setObjectName("menuDB")
        self.menuLoad_Data_From_DB = QtWidgets.QMenu(self.menuDB)
        self.menuLoad_Data_From_DB.setObjectName("menuLoad_Data_From_DB")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLoadStrobe_on_off_time = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoadStrobe_on_off_time.setIcon(icon)
        self.actionLoadStrobe_on_off_time.setObjectName("actionLoadStrobe_on_off_time")
        self.actionLoadMCS_Cycle_Time = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/database3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoadMCS_Cycle_Time.setIcon(icon1)
        self.actionLoadMCS_Cycle_Time.setObjectName("actionLoadMCS_Cycle_Time")
        self.actionLoadMCS_PCB_Status = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/database2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoadMCS_PCB_Status.setIcon(icon2)
        self.actionLoadMCS_PCB_Status.setObjectName("actionLoadMCS_PCB_Status")
        self.menuLoad_Data_From_DB.addAction(self.actionLoadStrobe_on_off_time)
        self.menuLoad_Data_From_DB.addAction(self.actionLoadMCS_Cycle_Time)
        self.menuLoad_Data_From_DB.addAction(self.actionLoadMCS_PCB_Status)
        self.menuDB.addAction(self.menuLoad_Data_From_DB.menuAction())
        self.menubar.addAction(self.menuDB.menuAction())
        self.toolBar.addAction(self.actionLoadStrobe_on_off_time)
        self.toolBar.addAction(self.actionLoadMCS_PCB_Status)
        self.toolBar.addAction(self.actionLoadMCS_Cycle_Time)

        self.retranslateUi(MainWindow)
        self.actionLoadStrobe_on_off_time.triggered.connect(MainWindow.menu_load_strobe_on_off_time) # type: ignore
        self.actionLoadMCS_Cycle_Time.triggered.connect(MainWindow.menu_load_mcs_cycle_time) # type: ignore
        self.actionLoadMCS_PCB_Status.triggered.connect(MainWindow.menu_load_mcs_pcb_status) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Visual Analyzer"))
        self.menuDB.setTitle(_translate("MainWindow", "DB"))
        self.menuLoad_Data_From_DB.setTitle(_translate("MainWindow", "Load Data From DB"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.actionLoadStrobe_on_off_time.setText(_translate("MainWindow", "Strobe on off time"))
        self.actionLoadMCS_Cycle_Time.setText(_translate("MainWindow", "MCS Cycle Time"))
        self.actionLoadMCS_PCB_Status.setText(_translate("MainWindow", "MCS PCB Status"))
import visual_analyzer_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
